sequenceDiagram
Title: DID Delegate
  autonumber
  participant App as Application
  participant SDK as DID JS SDK
  participant HSDK as Hashgraph JS SDK
  participant HCS as Hedera Consensus Service
  participant HMN as Hedera Mirror Node


alt Delegate a DID

App ->> HSDK: Build Client (Set account that will pay for transaction)
App ->> HSDK: Generate New Owner DID Private Key (DPK)
App ->> SDK: Register DID with DPK
SDK ->> SDK: Build did identifier with topic id
SDK ->> SDK: Create DID owner Event <br> with identifier
SDK ->> HSDK: Build DID owner Event Transaction  <br> signed with DPK
SDK ->> HSDK: Execute above transaction with Client
HSDK ->> HCS: Submit message to Topic
HCS ->> HMN: Propagate Message <br> to Topic
SDK ->> App: Send DID Identifier <br> e.g. (did:hedera:testnet:z6Mk.._0.0.2..)
end