sequenceDiagram
Title: DID Resolve
  autonumber
  participant App as Application
  participant SDK as DID JS SDK
  participant HSDK as Hashgraph JS SDK
  participant HMN as Hedera Mirro Node


alt resolve a DID
App ->> HSDK: Build Client (No Hedera account info needed)

App ->> SDK: Create HCS DID Object with <br> DID Identifier <br> e.g. (did:hedera:testnet:z6Mk.._0.0.2..)
App ->> SDK: Resolve a DID
SDK ->> SDK: Extract topic id from DID
SDK ->> HSDK: Subscribe to Topic
HSDK ->> HMN: Subscribe to Topic 
HMN -->> HSDK: receive all messages
HSDK -->> SDK: receive all messages
SDK ->> SDK: extract all Events from messages
SDK ->> SDK: proccess events
SDK ->> SDK: generate DID Document
SDK ->> App: send DID Document
end


