sequenceDiagram
Title: Revoke DID attribute
  autonumber
  participant App as Application
  participant SDK as DID JS SDK
  participant HSDK as Hashgraph JS SDK
  participant HCS as Hedera Consensus Service
  participant HMN as Hedera Mirror Node


alt Revoke DID attribute

App ->> SDK: Send Revoke attribute DID request with identifier and PK
SDK ->> HSDK: Build Client (Set account that will pay for transaction)
SDK ->> HMN: Send Revoke DID attribute Event
HMN ->> SDK: Ack
SDK ->> App: Send DID Identifier
end