sequenceDiagram
Title: Delete DID
  autonumber
  participant App as Application
  participant SDK as DID JS SDK
  participant HSDK as Hashgraph JS SDK
  participant HCS as Hedera Consensus Service
  participant HMN as Hedera Mirror Node


alt Delete DID

App ->> SDK: Send Delete DID request with identifier and DID Private Key
SDK ->> HSDK: Build Client (Set account that will pay for transaction)
SDK ->> HCS: Send Delete DID Event message
HCS ->> HMN: Propagate Message <br> to Topic
SDK ->> HSDK: Subscribe to the topic and <br /> wait till message is successfully submited
SDK -->> App: Send DID Identifier
end