# This workflow will run tests using node and then publish a package to GitHub Packages when a tag is created.
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Release

on:
  push:
    tags: [ 'v*' ]

  workflow_dispatch:
    inputs:
      version:
        type: string
        description: Test Version String (No release to Maven Central)
        required: true
      dry-run-enabled:
        description: 'Enable dry run for publishing (does not publish to npmjs)'
        required: false
        default: false
        type: boolean

defaults:
  run:
    shell: bash

permissions:
  contents: read
  id-token: write
  packages: write

jobs:
  build:
    runs-on: decentralized-identity-linux-medium
    strategy:
      matrix:
        node: [ '14', '16' ]
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@17d0e2bd7d51742c71671bd19fa12bdc9d40a3d6 # v2.8.1
        with:
          egress-policy: audit

      - name: Checkout Code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Setup Node
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          cache: 'npm'
          node-version: ${{ matrix.node }}

      - name: Run CI
        run: npm ci

      - name: Run Tests
        run: npm test
        env:
          OPERATOR_ID: ${{ secrets.OPERATOR_ID }}
          OPERATOR_KEY: ${{ secrets.OPERATOR_KEY }}

  build-npm-package:
    needs: build
    runs-on: decentralized-identity-linux-medium
    outputs:
      npm-artifact-name: ${{ steps.set-publish-data.outputs.artifact-name }}
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@20cf305ff2072d973412fa9b1e3a4f227bda3c76 # v2.14.0
        with:
          egress-policy: audit

      - name: Prepare Runner
        uses: pandaswhocode/initialize-github-job@ed4a98646fe0235e6ecf3af5414b355d2abe3bf3 # v1.0.3
        with:
          checkout: 'true'
          checkout-ref: '${{ github.ref }}'
          checkout-fetch-depth: '1'
          checkout-token: '${{ secrets.GITHUB_TOKEN }}'
          setup-node: 'true'
          node-version: '14'

      - name: Setup JQ
        uses: step-security/install-jq-action@fd50feb4e8cd2b0e1e72df42db468e62c71d58f4 # v3.2.0
        with:
          version: 1.7

      - name: Run CI
        run: npm ci

      - name: Set Publish Data
        id: set-publish-data
        run: |
          VERSION=$(jq -r '.version' './package.json')
          NPM_PACKAGE_NAME="hashgraph-did-sdk-js-${VERSION}.tgz"
          echo "artifact-name=${NPM_PACKAGE_NAME}" >> "${GITHUB_OUTPUT}"

      - name: Build npm project
        id: npm-pack
        run: npm pack

      - name: Upload DID-SDK-JS Package Artifact
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: npm-package
          path: ./${{ steps.set-publish-data.outputs.artifact-name }}
          if-no-files-found: error

  publish-npm-package:
    runs-on: ubuntu-latest
    needs:
      - build-npm-package
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@20cf305ff2072d973412fa9b1e3a4f227bda3c76 # v2.14.0
        with:
          egress-policy: audit

      - name: Prepare Runner
        uses: pandaswhocode/initialize-github-job@ed4a98646fe0235e6ecf3af5414b355d2abe3bf3 # v1.0.3
        with:
          checkout: 'true'
          checkout-ref: '${{ github.ref }}'
          checkout-fetch-depth: '1'
          checkout-token: '${{ secrets.GITHUB_TOKEN }}'
          setup-node: 'true'
          node-version: '14'
          node-registry: 'https://registry.npmjs.org'

      - name: Install NPM latest
        run: npm install -g npm@11.7.0

      - name: Download DID SDK JS NPM Package
        uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7.0.0
        with:
          name: npm-package

      - name: Publish NPM Package
        run: |
          args="--access=public"
          if [[ "${{ inputs.dry-run-enabled || 'false' }}" == "true" ]]; then
            args="${args} --dry-run"
          fi

          package="${{ needs.build-npm-package.outputs.npm-artifact-name }}"
          echo "::group::Publishing package: ${package} with args: ${args}"
          npm publish ${package} ${args}
          echo "::endgroup::"
