name: Test

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '14', '16' ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          cache: 'npm'
          node-version: ${{ matrix.node }}
      - run: npm ci
      - run: npm test
        env:
          OPERATOR_ID: ${{ secrets.OPERATOR_ID }}
          OPERATOR_KEY: ${{ secrets.OPERATOR_KEY }}

