name: Test

on:
  pull_request:
    branches: 
      - develop 
  push:
    branches: 
      - develop 

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '16' ]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: install dependencies
        run: npm ci
      - name: build
        run: npm run build --if-present
      - name: run unit test  
        run: npm run test:unit

